object_classes:

  barrel:
    keypoints_num: 8
    object_keypoints_mean:
      [0.38, 0.38, 0.1, 0.1, -0.38, -0.38, -0.1, -0.1,
      2, -2, -2, 2, 2, -2, -2, 2, 
      0, 0, 1, 1, 0, 0, 1, 1]

    object_mean_shape:
      [0.6, 0.6, 0.9]

    aliases: []
    marker_color: [1.0, 0.0, 0.0]

  pylon:
    keypoints_num: 5
    object_keypoints_mean:
      [0.38, 0.38, 0.1, 0.1, -0.38, 
      2, -2, -2, 2, 2,  
      0, 0, 1, 1, 0]

    object_mean_shape:
     [0.38, 0.38, 1]

    aliases: []
    marker_color: [0.0, 1.0, 0.0]

#--------------------------------------------------------------------------------------------
# other configs 
#--------------------------------------------------------------------------------------------

# whether to fine tune object pose using Levenberg Marquardt
# do_fine_tune_object_pose_using_lm: false 
do_fine_tune_object_pose_using_lm: true       

# The directory where result files are saved per object
result_dir_path_object_map: "/tmp/orcvio/results/"
